services:
  - type: web
    name: schoollms-backend
    runtime: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: MONGO_URI
        value: "MASUKKAN_MONGO_URI_ANDA_DI_SINI"
